apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pg-rails
  labels:
    app: pg-rails
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pg-rails
    spec:
      containers:
      - name: pg-rails
        image: jacobo/pg-rails:latest
        env:
        #TODO: specify a secret key base too
        #TODO: how do I make a composite environment variable?
        - name: MY_APP_VERSION
          value: v1 #increment this to "cheat" and get a re-deployment
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: rds-pg-db-url
              key: database-url
        # - name: DB_HOST
        #   value: pg-rails-service #works because of kubeDNS and the name we gave our DB deployments
        # - name: DB_PASSWORD
        #   valueFrom:
        #     secretKeyRef:
        #       name: pg-db-secret
        #       key: postgres-password
        ports:
        - containerPort: 5000
          name: pg-rails #TODO: why do ports need names?
#TODO: do we want a volume so nginx can serve static assets?